project_id = "oivhknarldehmztqjwmf"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.sign-in-with-phone]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false